import type { ProductionRow, ProductionStatus, RewindStep } from '@/lib/database.types';

/**
 * What the pipeline does after Gate 1, expressed for a person.
 *
 * This is a deliberate mirror of `GRAPH` in
 * `apps/pipeline/pipeline/driver/graph.py`, and it is a mirror of the *step
 * names* rather than of `productions.stage`. That distinction is the whole
 * design of this file. `stage` is unconstrained free text -- `render 42%`,
 * `fal generating (kling)`, `presenter rendered`, `checked` -- written by
 * whichever activity happened to be running, with no check constraint behind
 * it. Building a timeline on it would mean string-matching a value nobody
 * promised to keep stable. `run_state.step` is a closed set of twelve names
 * that the driver cannot leave, so it is what decides where a production is;
 * `stage` is only ever shown as a live sub-label.
 *
 * Pure functions on purpose, like `features/trends/controls.ts`: what a
 * production is doing, and which controls are legal, are both easy to get
 * subtly wrong and impossible to check by looking at the page.
 *
 * The control predicates below are a copy of the guards in
 * `20260907150000_production_visibility.sql`, and the copy is for feedback
 * only -- so the owner sees *why* something is unavailable instead of being
 * refused after clicking. Postgres is what actually enforces them.
 */

/** A step as the driver knows it. Mirrors the keys of `GRAPH`. */
export type GraphStep =
  | 'write_script'
  /** The uploaded lane's only step of its own. Everything after it is shared. */
  | 'check_upload'
  | 'open_script_gate'
  | 'await_script'
  | 'submit_render'
  | 'poll_render'
  | 'fetch_and_qc'
  | 'generate_copy'
  | 'open_gate2'
  | 'await_gate2'
  | 'publish'
  | 'poll_publish'
  | 'published'
  | 'rejected'
  | 'parked'
  | 'cancelled'
  | 'publishing_disabled';

/** `START` in graph.py: a row with no step yet has not begun this one.
 *
 * This moved when the script gate landed. A production no longer opens by
 * spending money — it opens by drafting words for a person to read, and
 * `resume_step()` in Postgres carries the same default. If the three ever
 * disagree, a fresh row is sent to the wrong step. */
export const FIRST_STEP: GraphStep = 'write_script';

/**
 * Where an uploaded cut starts instead.
 *
 * `create_upload_production` writes this into `run_state.step` at insert, so
 * unlike `FIRST_STEP` it is never actually reached as a default — it is here so
 * that a row which somehow arrived without a step is placed at its own lane's
 * first step rather than at a render it must never reach.
 */
export const FIRST_UPLOAD_STEP: GraphStep = 'check_upload';

export const TERMINAL_STEPS = [
  'published',
  'rejected',
  'parked',
  'cancelled',
  'publishing_disabled',
] as const satisfies readonly GraphStep[];

export type TerminalStep = (typeof TERMINAL_STEPS)[number];

export function isTerminalStep(step: string): step is TerminalStep {
  return (TERMINAL_STEPS as readonly string[]).includes(step);
}

export type StepState =
  /** Not reached yet. */
  | 'pending'
  /** The worker is on it now. */
  | 'active'
  /** Reached, and waiting on something outside the pipeline — a person. */
  | 'waiting'
  | 'done'
  | 'failed'
  /** Reached, and deliberately not done. Publishing being switched off. */
  | 'skipped';

export type StepKey = 'queued' | 'uploaded' | 'script' | 'render' | 'check' | 'copy' | 'gate2' | 'publish' | 'done';

export interface PipelineStep {
  key: StepKey;
  label: string;
  /** One line saying what happens here, shown under the label. */
  description: string;
  /** The driver steps this one covers. */
  graphSteps: readonly GraphStep[];
  /** True where the pipeline stops for a person rather than for a machine. */
  isGate?: boolean;
}

/**
 * The timeline skeleton. Every step is rendered, including ones not reached
 * yet -- the same choice `RunBreakdown` makes in showing every trend stage
 * including the zeroes. A step that is missing from the page is a step nobody
 * can ask about.
 */
export const PIPELINE_STEPS: readonly PipelineStep[] = [
  {
    key: 'queued',
    label: 'Queued',
    description: 'The idea is approved and waiting for a worker to pick it up.',
    graphSteps: [],
  },
  {
    key: 'script',
    label: 'Script — your approval',
    description: 'The narration is drafted for you to read and edit. Nothing is rendered until you approve it.',
    graphSteps: ['write_script', 'open_script_gate', 'await_script'],
    isGate: true,
  },
  {
    key: 'render',
    label: 'Rendering',
    description: 'The video is generated by the backend this style uses.',
    graphSteps: ['submit_render', 'poll_render'],
  },
  {
    key: 'check',
    label: 'Download and quality check',
    description: 'The cut is fetched, stored, and checked for the faults a person should not have to catch.',
    graphSteps: ['fetch_and_qc'],
  },
  {
    key: 'copy',
    label: 'Platform copy',
    description: 'A caption, title and description written separately for each platform.',
    graphSteps: ['generate_copy'],
  },
  {
    key: 'gate2',
    label: 'Gate 2 — your sign-off',
    description: 'Nothing publishes until a person approves the finished cut.',
    graphSteps: ['open_gate2', 'await_gate2'],
    isGate: true,
  },
  {
    key: 'publish',
    label: 'Publishing',
    description: 'Posted to each enabled platform, then confirmed.',
    graphSteps: ['publish', 'poll_publish'],
  },
  {
    key: 'done',
    label: 'Finished',
    description: 'Where this production ended up.',
    graphSteps: ['published', 'rejected', 'parked', 'cancelled', 'publishing_disabled'],
  },
] as const;

/**
 * The same timeline for a cut somebody uploaded.
 *
 * A separate skeleton rather than the one above with three steps greyed out,
 * because "skipped" is not what happened to them. An upload did not skip the
 * script gate — there was never a script, and nothing was ever going to render
 * it. Drawing steps that could not have applied would invite the reader to ask
 * why they did not happen, which is the opposite of what a timeline is for.
 *
 * Everything from `check` down is the same object as the generated lane's, and
 * that is the point: an uploaded production and a rendered one are the same
 * production from the quality check onwards.
 */
export const UPLOAD_PIPELINE_STEPS: readonly PipelineStep[] = [
  {
    key: 'uploaded',
    label: 'Uploaded',
    description: 'You supplied the finished cut. No idea, no script and no render — it starts here.',
    graphSteps: [],
  },
  {
    key: 'check',
    label: 'Quality check',
    description: 'The file is inspected for the faults a person should not have to catch by watching.',
    graphSteps: ['check_upload'],
  },
  {
    key: 'copy',
    label: 'Platform copy',
    description: 'A caption, title and description written for each platform, from the description you gave.',
    graphSteps: ['generate_copy'],
  },
  {
    key: 'gate2',
    label: 'Gate 2 — your sign-off',
    description: 'Nothing publishes until a person approves the finished cut.',
    graphSteps: ['open_gate2', 'await_gate2'],
    isGate: true,
  },
  {
    key: 'publish',
    label: 'Publishing',
    description: 'Posted to each enabled platform, then confirmed.',
    graphSteps: ['publish', 'poll_publish'],
  },
  {
    key: 'done',
    label: 'Finished',
    description: 'Where this production ended up.',
    graphSteps: ['published', 'rejected', 'parked', 'cancelled', 'publishing_disabled'],
  },
] as const;

/** Which skeleton this production is drawn against. */
export function pipelineStepsFor(production: Pick<ProductionLike, 'source'>): readonly PipelineStep[] {
  return production.source === 'upload' ? UPLOAD_PIPELINE_STEPS : PIPELINE_STEPS;
}

function indexMap(steps: readonly PipelineStep[]): Map<GraphStep, number> {
  return new Map(steps.flatMap((step, index) => step.graphSteps.map((g) => [g, index] as const)));
}

const STEP_INDEX = indexMap(PIPELINE_STEPS);
const UPLOAD_STEP_INDEX = indexMap(UPLOAD_PIPELINE_STEPS);

/**
 * Which display step a driver step belongs to, in one skeleton.
 *
 * Takes the steps rather than reading a module-level map, because the two
 * skeletons number their rows differently: `generate_copy` is index 4 in the
 * generated lane and index 2 in the uploaded one, and a position read against
 * the wrong one puts the whole timeline out by two.
 */
export function stepIndexOf(graphStep: string, steps: readonly PipelineStep[] = PIPELINE_STEPS): number {
  const map = steps === UPLOAD_PIPELINE_STEPS ? UPLOAD_STEP_INDEX : STEP_INDEX;
  return map.get(graphStep as GraphStep) ?? 0;
}

// ---------------------------------------------------------------------------
// Reading a production
// ---------------------------------------------------------------------------

type ProductionLike = Pick<
  ProductionRow,
  | 'source'
  | 'status'
  | 'stage'
  | 'run_state'
  | 'error'
  | 'task_id'
  | 'video_url'
  | 'paused_at'
  | 'superseded_by'
  | 'lease_expires_at'
  | 'created_at'
  | 'updated_at'
>;

function runState(production: ProductionLike): Record<string, unknown> {
  return (production.run_state ?? {}) as Record<string, unknown>;
}

function readString(state: Record<string, unknown>, key: string): string | null {
  const value = state[key];
  return typeof value === 'string' && value ? value : null;
}

/** The step a row with none yet is treated as being at. */
function firstStepFor(production: Pick<ProductionLike, 'source'>): GraphStep {
  return production.source === 'upload' ? FIRST_UPLOAD_STEP : FIRST_STEP;
}

/** Where the driver has this row now. */
export function currentGraphStep(production: ProductionLike): GraphStep {
  return (readString(runState(production), 'step') as GraphStep | null) ?? firstStepFor(production);
}

/**
 * The step a stopped production stopped on.
 *
 * A terminal overwrites `run_state.step` with its own name, so a parked row
 * says only "parked". `previous_step` is written by the engine before it
 * enters a terminal precisely so this question has an answer -- without it the
 * timeline could not place a failure, and neither could `retry_production`.
 */
export function stoppedAtStep(production: ProductionLike): GraphStep {
  const state = runState(production);
  const step = currentGraphStep(production);
  if (!isTerminalStep(step)) return step;
  return (readString(state, 'previous_step') as GraphStep | null) ?? firstStepFor(production);
}

/** Has the worker actually started on this row, or is it still waiting? */
export function hasStarted(production: ProductionLike): boolean {
  return readString(runState(production), 'step') !== null;
}

/**
 * How long a fresh row may sit untouched before that means something.
 *
 * The dispatcher polls every `driver_poll_seconds` — five by default — so a
 * row that nothing has claimed after this long is not "about to start". It is
 * evidence that no worker is running, and the UI has to say so rather than
 * promise a start that is not coming. Found the hard way: two approved ideas
 * sat at "Starting… within a few seconds" for hours while no worker existed.
 */
export const WORKER_GRACE_MS = 30_000;

/**
 * Approved, opened, and never picked up.
 *
 * The production equivalent of `isUnclaimed` for trend runs. A queued row with
 * no step whose `created_at` is past the grace has been waiting on a worker
 * that has not come, and nothing on the row will change until one does.
 */
export function isUnclaimed(production: ProductionLike, now: number = Date.now()): boolean {
  if (production.status !== 'queued' || production.paused_at !== null) return false;

  // An uploaded cut cannot be recognised by having no step: it is inserted
  // *with* one, because `create_upload_production` puts it at `check_upload`
  // rather than letting it default into the render lane. So the marker is
  // different — still queued, still at its own first step, and not currently
  // held by a worker.
  //
  // Measured from `updated_at` rather than `created_at`, and this is the part
  // that has to be right: the check itself legitimately runs for minutes on a
  // large file, and a worker holds an hour's lease while it does. Reading
  // `created_at` would call every slow upload abandoned.
  if (production.source === 'upload') {
    if (currentGraphStep(production) !== FIRST_UPLOAD_STEP) return false;
    if (isLeased(production, now)) return false;
    const touched = production.updated_at || production.created_at;
    if (!touched) return false;
    return now - new Date(touched).getTime() > WORKER_GRACE_MS;
  }

  if (hasStarted(production)) return false;
  if (!production.created_at) return false;
  return now - new Date(production.created_at).getTime() > WORKER_GRACE_MS;
}

export function isPaused(production: ProductionLike): boolean {
  return production.paused_at !== null;
}

/** The worker is holding this row right now, so its state is about to change. */
export function isLeased(production: ProductionLike, now: number = Date.now()): boolean {
  if (!production.lease_expires_at) return false;
  return new Date(production.lease_expires_at).getTime() > now;
}

/**
 * A render that may already have been billed for.
 *
 * `task_id` is set by `claim_render_slot` at the moment of submitting, so it
 * is exactly the marker for "money may be moving". This is why cancel is
 * refused here -- see `cancel_production`.
 */
export function isRenderInFlight(production: ProductionLike): boolean {
  if (production.task_id === null) return false;
  const step = currentGraphStep(production);
  return step === 'submit_render' || step === 'poll_render' || step === 'fetch_and_qc';
}

/** Finished, one way or another. Nothing more happens without a person. */
export function isFinished(production: ProductionLike): boolean {
  const step = currentGraphStep(production);
  if (step === 'published' || step === 'rejected' || step === 'cancelled') return true;
  return production.status === 'published' || production.status === 'rejected' || production.status === 'cancelled';
}

export function isStopped(production: ProductionLike): boolean {
  return production.status === 'parked' || production.status === 'failed';
}

/**
 * Held rather than failed.
 *
 * `publishing_disabled` keeps `status = 'approved'` on purpose, so these rows
 * are a queryable backlog holding a finished cut and its copy. Showing it as a
 * failure would be wrong in the one way that matters: it would suggest
 * something needs fixing.
 */
export function isHeldForPublishing(production: ProductionLike): boolean {
  return currentGraphStep(production) === 'publishing_disabled';
}

export function isAtGate2(production: ProductionLike): boolean {
  return production.status === 'awaiting_review' || production.status === 'qc_failed';
}

/**
 * Stopped at the script gate, waiting for a person to approve the words.
 *
 * Reads the status rather than the step, for the same reason `isAtGate2` does:
 * the status is what `claim_production` filters on, so it is the fact that
 * actually decides whether the driver will touch this row.
 */
export function isAtScriptGate(production: ProductionLike): boolean {
  return production.status === 'awaiting_script';
}

/**
 * Whether the script is still an input to anything.
 *
 * A copy of `script_is_editable` in the script-gate migration, and a copy for
 * feedback only — Postgres refuses the write regardless. `task_id` is the
 * load-bearing half: it is set at the instant of submitting to a render
 * backend, so once it exists the words have been paid for and editing them
 * would only make the record wrong.
 */
export function isScriptEditable(production: ProductionLike): boolean {
  if (production.superseded_by !== null) return false;
  if (production.task_id !== null) return false;
  const step = currentGraphStep(production);
  if (step !== 'write_script' && step !== 'open_script_gate' && step !== 'await_script') return false;
  return (
    production.status === 'queued' ||
    production.status === 'running' ||
    production.status === 'awaiting_script' ||
    production.status === 'parked' ||
    production.status === 'failed'
  );
}

/** Why the script cannot be edited, in words an owner can act on. */
export function scriptLockReason(production: ProductionLike): string | null {
  if (isScriptEditable(production)) return null;
  if (production.superseded_by !== null) {
    return 'This production was re-run. Edit the script on the one that replaced it.';
  }
  if (production.task_id !== null) {
    return 'The render has already been submitted and paid for against these words. Make the idea again to change them.';
  }
  return 'This production is past the script gate, so its script is no longer an input to anything.';
}

// ---------------------------------------------------------------------------
// The timeline
// ---------------------------------------------------------------------------

export interface TimelineStep extends PipelineStep {
  state: StepState;
}

export function buildTimeline(production: ProductionLike): TimelineStep[] {
  const steps = pipelineStepsFor(production);
  const step = currentGraphStep(production);
  const terminal = isTerminalStep(step);
  const position = stepIndexOf(terminal ? stoppedAtStep(production) : step, steps);
  const stopped = isStopped(production);
  const held = isHeldForPublishing(production);
  const started = hasStarted(production);
  const paused = isPaused(production);

  return steps.map((pipelineStep, index) => ({
    ...pipelineStep,
    state: stateFor({ pipelineStep, index, position, terminal, stopped, held, started, paused, production, step }),
  }));
}

function stateFor(args: {
  pipelineStep: PipelineStep;
  index: number;
  position: number;
  terminal: boolean;
  stopped: boolean;
  held: boolean;
  started: boolean;
  paused: boolean;
  production: ProductionLike;
  step: GraphStep;
}): StepState {
  const { pipelineStep, index, position, terminal, stopped, held, started, paused, production, step } = args;

  // The last step is where a production ends up, so it is only ever reached.
  if (pipelineStep.key === 'done') {
    if (step === 'published') return 'done';
    if (step === 'cancelled' || step === 'rejected') return 'failed';
    if (held) return 'skipped';
    if (stopped) return 'failed';
    return 'pending';
  }

  // The first step of either lane is the only one that is complete before the
  // driver has touched the row: Gate 1 has already happened, or the file has
  // already been uploaded.
  if (pipelineStep.key === 'queued') {
    return started || terminal ? 'done' : 'active';
  }
  // An upload's first row is done the moment the row exists — the file is in
  // the bucket before `create_upload_production` will open one, so unlike a
  // queued production there is nothing still to arrive.
  if (pipelineStep.key === 'uploaded') return 'done';

  if (index < position) return 'done';

  if (index === position) {
    if (stopped) return 'failed';
    if (step === 'cancelled') return 'failed';
    // `held` is deliberately not a case here. A production only reaches
    // `publishing_disabled` by passing Gate 2 -- `_gate2_outcome` routes there
    // when the status is `approved` -- so the step it is resting on was
    // completed, and it is only what comes *after* it that is skipped.
    if (paused) return 'waiting';
    // A gate with its decision still outstanding is waiting on a person, which
    // is not the same as the machine working. Both gates read their status
    // rather than their step: the status is what the claim query filters on,
    // so it is what decides whether anything is actually going to happen.
    if (pipelineStep.key === 'gate2' && isAtGate2(production)) return 'waiting';
    if (pipelineStep.key === 'script' && isAtScriptGate(production)) return 'waiting';
    return terminal ? 'done' : 'active';
  }

  // Publishing is switched off, so everything past the gate is deliberately
  // not going to happen rather than merely not having happened yet.
  if (held && pipelineStep.key === 'publish') return 'skipped';
  return 'pending';
}

// ---------------------------------------------------------------------------
// Saying it in a sentence
// ---------------------------------------------------------------------------

export interface ProductionVerdict {
  headline: string;
  detail: string | null;
  /** Drives the badge colour. */
  tone: 'working' | 'waiting' | 'good' | 'bad' | 'held';
}

export function describeProduction(production: ProductionLike, now: number = Date.now()): ProductionVerdict {
  const step = currentGraphStep(production);
  const stage = production.stage?.trim() || null;

  if (production.superseded_by) {
    return {
      headline: 'Superseded',
      detail: 'This production was re-run. A newer one replaced it.',
      tone: 'held',
    };
  }
  if (production.status === 'cancelled') {
    return { headline: 'Cancelled', detail: 'An owner stopped this production.', tone: 'bad' };
  }
  if (isStopped(production)) {
    return {
      headline: 'Stopped — needs you',
      detail: production.error ?? 'The pipeline stopped and is waiting for a person.',
      tone: 'bad',
    };
  }
  if (isHeldForPublishing(production)) {
    return {
      headline: 'Held — publishing is off',
      detail: 'The cut and its per-platform copy are ready. Nothing is wrong; publishing is switched off.',
      tone: 'held',
    };
  }
  if (production.status === 'published') {
    return { headline: 'Published', detail: 'This production is finished.', tone: 'good' };
  }
  if (production.status === 'rejected') {
    return { headline: 'Rejected at Gate 2', detail: 'Nothing was published.', tone: 'bad' };
  }
  if (isPaused(production)) {
    return {
      headline: 'Paused',
      detail: isRenderInFlight(production)
        ? 'Paused by an owner. The render already running at the provider carries on — pausing does not stop it.'
        : 'Paused by an owner. Nothing runs until it is resumed.',
      tone: 'waiting',
    };
  }
  if (isAtScriptGate(production)) {
    return {
      headline: 'Script — waiting for you',
      detail:
        'The narration is drafted. Read it, edit it if you want to, and approve it — nothing renders until you do.',
      tone: 'waiting',
    };
  }
  if (isAtGate2(production)) {
    return {
      headline: production.status === 'qc_failed' ? 'Gate 2 — quality check failed' : 'Gate 2 — waiting for you',
      detail:
        production.status === 'qc_failed'
          ? 'The cut is ready but failed its quality check. You can still approve it.'
          : 'The finished cut is waiting for your sign-off.',
      tone: 'waiting',
    };
  }
  if (isUnclaimed(production, now)) {
    return {
      headline: 'Waiting for a worker',
      detail:
        production.source === 'upload'
          ? 'The file is uploaded, but no pipeline worker has picked it up to check it. The worker is probably not running — nothing here changes until it is.'
          : 'Approved, but no pipeline worker has picked this up. The worker is probably not running — nothing here changes until it is.',
      tone: 'waiting',
    };
  }
  if (!hasStarted(production)) {
    return {
      headline: 'Starting',
      detail: 'Approved. A worker picks this up within a few seconds.',
      tone: 'working',
    };
  }

  const steps = pipelineStepsFor(production);
  const label = steps[stepIndexOf(step, steps)]?.label ?? 'Working';
  return { headline: label, detail: stage, tone: 'working' };
}

/** Render progress, 0-100, when the backend reports it. */
export function renderProgress(production: ProductionLike): number | null {
  const value = runState(production).progress;
  if (typeof value !== 'number' || Number.isNaN(value)) return null;
  return Math.max(0, Math.min(100, value));
}

// ---------------------------------------------------------------------------
// Which controls are legal
// ---------------------------------------------------------------------------

export type ControlAction = 'pause' | 'resume' | 'retry' | 'cancel' | 'rerun' | 'rewind';

export interface ControlAvailability {
  enabled: boolean;
  /** Why not, in words the owner can act on. Null when enabled. */
  reason: string | null;
}

const BUSY = 'The worker is running a step right now. This is available again in a moment.';

export function availableControls(production: ProductionLike): Record<ControlAction, ControlAvailability> {
  const paused = isPaused(production);
  const leased = isLeased(production);
  const finished = isFinished(production);
  const stopped = isStopped(production);
  const superseded = production.superseded_by !== null;
  const renderInFlight = isRenderInFlight(production);

  const ok: ControlAvailability = { enabled: true, reason: null };
  const no = (reason: string): ControlAvailability => ({ enabled: false, reason });

  return {
    pause: superseded
      ? no('This production was superseded by a re-run.')
      : paused
        ? no('Already paused.')
        : finished || production.status === 'failed'
          ? no('This production has finished.')
          : ok,

    resume: !paused ? no('This production is not paused.') : leased ? no(BUSY) : ok,

    retry: superseded
      ? no('This production was superseded by a re-run.')
      : !stopped
        ? no('Only a stopped production can be retried.')
        : leased
          ? no(BUSY)
          : ok,

    cancel: superseded
      ? no('This production was superseded by a re-run.')
      : finished
        ? no('This production has already finished.')
        : renderInFlight
          ? no(
              'A render is still running and has already been billed for. Wait for it to finish or stop, or pause it instead.',
            )
          : leased
            ? no(BUSY)
            : ok,

    rerun:
      production.source === 'upload'
        ? no(
            'This is an uploaded cut, so there is nothing to make again. Upload the video again to put a new one through Gate 2.',
          )
        : superseded
          ? no('This production has already been re-run.')
          : !canRerun(production)
            ? no('This production is still running. Cancel it first, or wait for it to finish.')
            : leased
              ? no(BUSY)
              : ok,

    rewind: superseded
      ? no('This production was superseded by a re-run.')
      : rewindableSteps(production).length === 0
        ? no('There is nothing to redo yet — this production has no finished cut.')
        : leased
          ? no(BUSY)
          : ok,
  };
}

function canRerun(production: ProductionLike): boolean {
  const finishedStatuses: readonly ProductionStatus[] = ['parked', 'cancelled', 'rejected', 'published', 'failed'];
  if (finishedStatuses.includes(production.status)) return true;
  return production.status === 'approved' && isHeldForPublishing(production);
}

/**
 * The steps this production has the artifacts to redo.
 *
 * `submit_render` is never among them: a fresh render costs money and belongs
 * to `rerun_production`, which opens a new row rather than overwriting the cut
 * that is already there.
 */
export function rewindableSteps(production: ProductionLike): RewindStep[] {
  const steps: RewindStep[] = [];
  if (production.task_id !== null) steps.push('fetch_and_qc');
  if (production.video_url !== null) steps.push('generate_copy', 'open_gate2');
  return steps;
}

export const REWIND_LABELS: Record<RewindStep, string> = {
  fetch_and_qc: 'Re-check the render',
  generate_copy: 'Rewrite the platform copy',
  open_gate2: 'Re-open Gate 2',
};

export const REWIND_DESCRIPTIONS: Record<RewindStep, string> = {
  fetch_and_qc: 'Download the existing render again and run the quality check over it. Costs nothing.',
  generate_copy: 'Throw away the current per-platform copy and write it again.',
  open_gate2: 'Clear the Gate 2 decision and put the cut back in front of a reviewer.',
};
