/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AppRouteImport } from './routes/_app';
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password';
import { Route as LoginRouteImport } from './routes/login';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as ResetPasswordRouteImport } from './routes/reset-password';
import { Route as AppClipsRouteImport } from './routes/_app/clips';
import { Route as AppQueueRouteImport } from './routes/_app/queue';
import { Route as AppReviewRouteImport } from './routes/_app/review';
import { Route as AppSettingsRouteImport } from './routes/_app/settings';
import { Route as AppProductionsProductionIdRouteImport } from './routes/_app/productions_.$productionId';
import { Route as AppQueueIdeaIdRouteImport } from './routes/_app/queue_.$ideaId';
import { Route as AppReviewProductionIdRouteImport } from './routes/_app/review_.$productionId';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any);
const AppClipsRoute = AppClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => AppRoute,
} as any);
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any);
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any);
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any);
const AppProductionsProductionIdRoute =
  AppProductionsProductionIdRouteImport.update({
    id: '/productions_/$productionId',
    path: '/productions/$productionId',
    getParentRoute: () => AppRoute,
  } as any);
const AppQueueIdeaIdRoute = AppQueueIdeaIdRouteImport.update({
  id: '/queue_/$ideaId',
  path: '/queue/$ideaId',
  getParentRoute: () => AppRoute,
} as any);
const AppReviewProductionIdRoute = AppReviewProductionIdRouteImport.update({
  id: '/review_/$productionId',
  path: '/review/$productionId',
  getParentRoute: () => AppRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/clips': typeof AppClipsRoute;
  '/queue': typeof AppQueueRoute;
  '/review': typeof AppReviewRoute;
  '/settings': typeof AppSettingsRoute;
  '/productions/$productionId': typeof AppProductionsProductionIdRoute;
  '/queue/$ideaId': typeof AppQueueIdeaIdRoute;
  '/review/$productionId': typeof AppReviewProductionIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/clips': typeof AppClipsRoute;
  '/queue': typeof AppQueueRoute;
  '/review': typeof AppReviewRoute;
  '/settings': typeof AppSettingsRoute;
  '/productions/$productionId': typeof AppProductionsProductionIdRoute;
  '/queue/$ideaId': typeof AppQueueIdeaIdRoute;
  '/review/$productionId': typeof AppReviewProductionIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_app': typeof AppRouteWithChildren;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/_app/clips': typeof AppClipsRoute;
  '/_app/queue': typeof AppQueueRoute;
  '/_app/review': typeof AppReviewRoute;
  '/_app/settings': typeof AppSettingsRoute;
  '/_app/productions_/$productionId': typeof AppProductionsProductionIdRoute;
  '/_app/queue_/$ideaId': typeof AppQueueIdeaIdRoute;
  '/_app/review_/$productionId': typeof AppReviewProductionIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/clips'
    | '/queue'
    | '/review'
    | '/settings'
    | '/productions/$productionId'
    | '/queue/$ideaId'
    | '/review/$productionId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/clips'
    | '/queue'
    | '/review'
    | '/settings'
    | '/productions/$productionId'
    | '/queue/$ideaId'
    | '/review/$productionId';
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/clips'
    | '/_app/queue'
    | '/_app/review'
    | '/_app/settings'
    | '/_app/productions_/$productionId'
    | '/_app/queue_/$ideaId'
    | '/_app/review_/$productionId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRoute: typeof AppRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app': {
      id: '/_app';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/forgot-password': {
      id: '/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reset-password': {
      id: '/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app/clips': {
      id: '/_app/clips';
      path: '/clips';
      fullPath: '/clips';
      preLoaderRoute: typeof AppClipsRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/queue': {
      id: '/_app/queue';
      path: '/queue';
      fullPath: '/queue';
      preLoaderRoute: typeof AppQueueRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/review': {
      id: '/_app/review';
      path: '/review';
      fullPath: '/review';
      preLoaderRoute: typeof AppReviewRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/settings': {
      id: '/_app/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof AppSettingsRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/productions_/$productionId': {
      id: '/_app/productions_/$productionId';
      path: '/productions/$productionId';
      fullPath: '/productions/$productionId';
      preLoaderRoute: typeof AppProductionsProductionIdRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/queue_/$ideaId': {
      id: '/_app/queue_/$ideaId';
      path: '/queue/$ideaId';
      fullPath: '/queue/$ideaId';
      preLoaderRoute: typeof AppQueueIdeaIdRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/review_/$productionId': {
      id: '/_app/review_/$productionId';
      path: '/review/$productionId';
      fullPath: '/review/$productionId';
      preLoaderRoute: typeof AppReviewProductionIdRouteImport;
      parentRoute: typeof AppRoute;
    };
  }
}

interface AppRouteChildren {
  AppClipsRoute: typeof AppClipsRoute;
  AppQueueRoute: typeof AppQueueRoute;
  AppReviewRoute: typeof AppReviewRoute;
  AppSettingsRoute: typeof AppSettingsRoute;
  AppProductionsProductionIdRoute: typeof AppProductionsProductionIdRoute;
  AppQueueIdeaIdRoute: typeof AppQueueIdeaIdRoute;
  AppReviewProductionIdRoute: typeof AppReviewProductionIdRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppClipsRoute: AppClipsRoute,
  AppQueueRoute: AppQueueRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProductionsProductionIdRoute: AppProductionsProductionIdRoute,
  AppQueueIdeaIdRoute: AppQueueIdeaIdRoute,
  AppReviewProductionIdRoute: AppReviewProductionIdRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
