/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AppRouteImport } from './routes/_app';
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password';
import { Route as LoginRouteImport } from './routes/login';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as ResetPasswordRouteImport } from './routes/reset-password';
import { Route as AppQueueRouteImport } from './routes/_app/queue';
import { Route as AppReviewRouteImport } from './routes/_app/review';
import { Route as AppSettingsRouteImport } from './routes/_app/settings';
import { Route as AppQueueIdeaIdRouteImport } from './routes/_app/queue.$ideaId';
import { Route as AppReviewProductionIdRouteImport } from './routes/_app/review.$productionId';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any);
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any);
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any);
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any);
const AppQueueIdeaIdRoute = AppQueueIdeaIdRouteImport.update({
  id: '/$ideaId',
  path: '/$ideaId',
  getParentRoute: () => AppQueueRoute,
} as any);
const AppReviewProductionIdRoute = AppReviewProductionIdRouteImport.update({
  id: '/$productionId',
  path: '/$productionId',
  getParentRoute: () => AppReviewRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/queue': typeof AppQueueRouteWithChildren;
  '/review': typeof AppReviewRouteWithChildren;
  '/settings': typeof AppSettingsRoute;
  '/queue/$ideaId': typeof AppQueueIdeaIdRoute;
  '/review/$productionId': typeof AppReviewProductionIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/queue': typeof AppQueueRouteWithChildren;
  '/review': typeof AppReviewRouteWithChildren;
  '/settings': typeof AppSettingsRoute;
  '/queue/$ideaId': typeof AppQueueIdeaIdRoute;
  '/review/$productionId': typeof AppReviewProductionIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_app': typeof AppRouteWithChildren;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/_app/queue': typeof AppQueueRouteWithChildren;
  '/_app/review': typeof AppReviewRouteWithChildren;
  '/_app/settings': typeof AppSettingsRoute;
  '/_app/queue/$ideaId': typeof AppQueueIdeaIdRoute;
  '/_app/review/$productionId': typeof AppReviewProductionIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/queue'
    | '/review'
    | '/settings'
    | '/queue/$ideaId'
    | '/review/$productionId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/queue'
    | '/review'
    | '/settings'
    | '/queue/$ideaId'
    | '/review/$productionId';
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/queue'
    | '/_app/review'
    | '/_app/settings'
    | '/_app/queue/$ideaId'
    | '/_app/review/$productionId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRoute: typeof AppRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app': {
      id: '/_app';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/forgot-password': {
      id: '/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reset-password': {
      id: '/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app/queue': {
      id: '/_app/queue';
      path: '/queue';
      fullPath: '/queue';
      preLoaderRoute: typeof AppQueueRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/review': {
      id: '/_app/review';
      path: '/review';
      fullPath: '/review';
      preLoaderRoute: typeof AppReviewRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/settings': {
      id: '/_app/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof AppSettingsRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/_app/queue/$ideaId': {
      id: '/_app/queue/$ideaId';
      path: '/$ideaId';
      fullPath: '/queue/$ideaId';
      preLoaderRoute: typeof AppQueueIdeaIdRouteImport;
      parentRoute: typeof AppQueueRoute;
    };
    '/_app/review/$productionId': {
      id: '/_app/review/$productionId';
      path: '/$productionId';
      fullPath: '/review/$productionId';
      preLoaderRoute: typeof AppReviewProductionIdRouteImport;
      parentRoute: typeof AppReviewRoute;
    };
  }
}

interface AppQueueRouteChildren {
  AppQueueIdeaIdRoute: typeof AppQueueIdeaIdRoute;
}

const AppQueueRouteChildren: AppQueueRouteChildren = {
  AppQueueIdeaIdRoute: AppQueueIdeaIdRoute,
};

const AppQueueRouteWithChildren = AppQueueRoute._addFileChildren(
  AppQueueRouteChildren,
);

interface AppReviewRouteChildren {
  AppReviewProductionIdRoute: typeof AppReviewProductionIdRoute;
}

const AppReviewRouteChildren: AppReviewRouteChildren = {
  AppReviewProductionIdRoute: AppReviewProductionIdRoute,
};

const AppReviewRouteWithChildren = AppReviewRoute._addFileChildren(
  AppReviewRouteChildren,
);

interface AppRouteChildren {
  AppQueueRoute: typeof AppQueueRouteWithChildren;
  AppReviewRoute: typeof AppReviewRouteWithChildren;
  AppSettingsRoute: typeof AppSettingsRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppQueueRoute: AppQueueRouteWithChildren,
  AppReviewRoute: AppReviewRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
