-- fal.ai as a second render backend, selectable per style preset.
--
-- `lane` is deliberately left alone. It describes the *look* -- stock,
-- generative, presenter -- and that is what the owner is choosing between at
-- Gate 1. Which backend produces that look is a separate axis, so it gets its
-- own column rather than overloading the one the review UI already groups by.

alter table public.style_presets
  add column if not exists render_mode text not null default 'mpt';

alter table public.style_presets drop constraint if exists style_presets_render_mode_check;
alter table public.style_presets add constraint style_presets_render_mode_check
  check (render_mode in ('mpt', 'fal_visuals', 'fal_full'));

comment on column public.style_presets.render_mode is
  $$Which backend renders this preset.
    'mpt'         - MoneyPrinterTurbo does everything (script, voice, visuals, captions, assembly).
    'fal_visuals' - fal generates the clips; they are uploaded to MPT and it assembles, voices and captions as usual.
    'fal_full'    - fal generates visuals and narration; we assemble and burn captions ourselves.$$;

-- Which backend actually ran. Recorded rather than inferred, because a preset
-- can be edited after the fact and because a parked production needs to say
-- what failed without the reader having to reconstruct it.
alter table public.productions
  add column if not exists render_backend text;

comment on column public.productions.render_backend is
  'The render_mode in force when this production ran. Kept even if the preset later changes.';

-- ---------------------------------------------------------------------------
-- Presets.
--
-- Costs are derived from fal's published per-second rates against a 20-40
-- second reel, which is why each carries a range rather than a figure. LTX-2.3
-- was chosen over a Veo-class model deliberately: the audio-native premium
-- tiers run $0.20-0.75 per second, which is $5-18 for one 24-second reel, or
-- $1,500-5,400 a month at ten a day. That is not a default anyone should be
-- able to pick by accident.
-- ---------------------------------------------------------------------------

insert into public.style_presets
  (slug, name, description, lane, video_source, render_mode,
   est_cost_min_usd, est_cost_max_usd, est_minutes, params, is_active, sort_order)
values
  (
    'fal-generative',
    'Generative (fal)',
    'Brand-new footage generated by fal, then voiced, captioned and assembled by the usual render path. Visuals nothing in the stock library can produce, with everything downstream unchanged.',
    'generative',
    'fal',
    'fal_visuals',
    0.80, 1.80, 12,
    jsonb_build_object(
      'fal', jsonb_build_object(
        'model', 'fal-ai/ltx-2.3/text-to-video/fast',
        'resolution', '1080p',
        'aspect_ratio', '9:16',
        'clip_seconds', 5,
        'clips', 6,
        'fps', 24
      ),
      -- Applied to the assembling MPT render. video_source is forced to
      -- "local" by the pipeline, since that is the only mode that accepts
      -- clips MPT did not fetch itself.
      'video_aspect', '9:16',
      'subtitle_enabled', true,
      'subtitle_position', 'bottom',
      'font_size', 60,
      'stroke_width', 1.5,
      'video_concat_mode', 'sequential',
      'video_transition_mode', 'FadeIn',
      'bgm_type', 'random',
      'bgm_volume', 0.15
    ),
    true,
    15
  ),
  (
    'fal-end-to-end',
    'Generative, end to end (fal)',
    'fal generates the visuals and the narration; captions and assembly are done in the pipeline. Bypasses the render service entirely, so its output is not comparable to the other lanes -- kept inactive until its quality has been judged against them.',
    'generative',
    'fal',
    'fal_full',
    1.60, 3.20, 15,
    jsonb_build_object(
      'fal', jsonb_build_object(
        'model', 'fal-ai/ltx-2.3/text-to-video',
        'resolution', '1080p',
        'aspect_ratio', '9:16',
        'clip_seconds', 5,
        'clips', 6,
        'fps', 24,
        'tts_model', 'fal-ai/elevenlabs/tts/turbo-v2.5',
        'burn_captions', true
      )
    ),
    -- Inactive on purpose, exactly as the presenter preset is: it is a second
    -- assembly path whose output has never been compared with the others, and
    -- an inactive preset cannot be approved by mistake.
    false,
    16
  )
on conflict (slug) do update
  set render_mode      = excluded.render_mode,
      video_source     = excluded.video_source,
      est_cost_min_usd = excluded.est_cost_min_usd,
      est_cost_max_usd = excluded.est_cost_max_usd,
      est_minutes      = excluded.est_minutes,
      params           = excluded.params,
      description      = excluded.description;
